#!/bin/bash

NAME=think++

if [ -z $1 ]; then
	echo "$0: must specify a version"
	exit 1
fi

echo 'Refreshing auto* stuff...'

./autogen.sh --no-configure >/dev/null 2>&1

echo Cleaning up.

rm -rf ../$NAME-$1.bak

if [ -d "../$NAME-$1" ]; then
	mv ../$NAME-$1 ../$NAME-$1.bak
	echo Warning: saved ../$NAME-$1 directory as ../$NAME-$1.bak.
	echo If important stuff is in there, get it out or it will be 
	echo deleted next time!
fi

make distclean
rm -f .#*
cd ..
echo Creating tarball in ../$NAME-$1.tar.gz

mv $NAME $NAME-$1

tar --exclude CVS --exclude .cvsignore --exclude autogen.sh \
	--exclude make_release --exclude autom4te.cache  \
	--exclude aclocal.m4 -chzf $NAME-$1.tar.gz $NAME-$1 

mv $NAME-$1 $NAME
